#!/usr/bin/env bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(cd "$SCRIPTDIR" && cd ../../ && pwd || exit)"
JSDIR="$ROOTDIR/aliem/lib/js"
rollup="$ROOTDIR/node_modules/.bin/rollup"

for dir in $JSDIR/*; do
    cd "$dir" || exit 0
    $rollup -c
done
