#!/usr/bin/env bash

# Globals
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR=$(cd "$SCRIPTDIR" && cd ../../ && pwd || exit)

declare server_ip
declare server_user
declare rsa_filename
declare base_theme_name
declare theme_name
declare local_plugins

# shellcheck disable=SC1090
{
    . "$SCRIPTDIR"/helpers || exit 1
    . "$SCRIPTDIR"/variables || exit 1
}

main() {

    prechecks

    if [[ $# == 0 ]]; then
        get_uploads
        get_database
        exit 0
    fi

    case "$1" in
        init)
            get_database
            get_plugins
            get_theme
            get_theme_base
            get_uploads
            ;;
        get)
            case "$2" in
                uploads)
                    get_uploads;;
                plugins)
                    get_plugins;;
                theme)
                    get_theme;;
                base-theme)
                    get_theme_base;;
                database)
                    get_database;;
                *)
                    h2 "'get' subcommmand must be either 'uploads', 'plugins', 'theme', or 'database'" && exit 0
            esac;;
        *)
            h2 "The only available commands are 'init' and 'get'" && exit 0
    esac
}

prechecks() {
    depcheck \
        rsync \
        ssh \
        ssh-add \
        ssh-keyscan

    # Check ownership of directories within wp-content
    if [[ $(find "$ROOTDIR"/wp-content -type d -not -user "$USER") ]]; then
        h2 'Need sudo priveledges to take ownership of wp-content directory'
        sudo chown -R "$USER" "$ROOTDIR"/wp-content
    fi

    # Check to make sure the SSH key exists
    [[ ! -f "$HOME/.ssh/$rsa_filename" ]] && ERROR "SSH keys have not been added to your SSH directory for this machine"

    # Prepare for SSH transfers
    eval "$(ssh-agent -s)" &>/dev/null
    ssh-add "$HOME/.ssh/$rsa_filename" &>/dev/null

    if [ -z "$(ssh-keygen -F "$server_ip")" ]; then
      ssh-keyscan -H "$server_ip" >> ~/.ssh/known_hosts
    fi
}

get_uploads() {
    h2 "Downloading uploads from server..."
    rsync --info=progress2 -auze "ssh" "$server_user@$server_ip:/home/$server_user/app/wp-content/uploads/" "$ROOTDIR/wp-content/uploads"
    h2 "Uploads Synced Successfully!"
}

get_plugins() {
    local plugin
    h2 "Retrieving plugins"
    for plugin in "${local_plugins[@]}"; do
        h3 "Retrieving plugin: $plugin"
        rsync --info=progress2 -aze "ssh" "$server_user@$server_ip:/home/$server_user/app/wp-content/plugins/$plugin" "$ROOTDIR/wp-content/plugins"
    done
}

get_theme() {
    h2 "Retrieving Theme"
    rsync --info=progress2 -aze "ssh" "$server_user@$server_ip:/home/$server_user/app/wp-content/themes/$theme_name" "$ROOTDIR/wp-content/themes"
}

get_theme_base() {
    h2 "Retrieving Base Theme"
    rsync --info=progress2 -aze "ssh" "$server_user@$server_ip:/home/$server_user/app/wp-content/themes/$base_theme_name" "$ROOTDIR/wp-content/themes"
}

get_database() {
    h2 "Exporting database..."
    ssh "$server_user@$server_ip" "cd ~/app && docker-compose exec wordpress wp db export /data/database.sql --allow-root"

    h2 "Downloading database to local machine..."
    rsync --info=progress2 -aze "ssh" "$server_user@$server_ip:/home/$server_user/app/data/database.sql" "$ROOTDIR/data/database.sql"

    h2 "Export complete!"
}

main "$@"
